### ISSUE TITLE
Your feeder was broken

### ISSUE THREAD

**Issue by Perlover** [j-chimienti/pollofeed#2]
Hi,

Right now i paid three times but feeder doesn't work. I do not even see the rod twitching...

**Comment by j-chimienti** [comment]
Thanks for letting me know. Send me payment request and I will refund your purchase. 

Headers: time paid_at, sat, acknowledged_at.
<img width="672" alt="screen shot 2019-03-04 at 10 11 23 pm" src="https://user-images.githubusercontent.com/16620120/53778356-6debda00-3eca-11e9-82c2-a445ad537551.png">

I looked into the invoices today and it seems the issue was the feeder was unresponsive for ~ 5 min.
(guessing these are your invoices paid at 5:41:36 PM, 5:42:33 PM, and 5:47:02 PM)

I was probably being dumb and updating server during daylight hours. I should stop doing this.

Additionally, I should do a better job of notifying users that the feeding was acknowledged. I will add a a light to the feeder to show that it should be spinning, and also send alert to user when acknowledged like I do when payment is successful
